### ISSUE TITLE
links in the docs lead to Error 404

### ISSUE THREAD

**Issue by chriskuku** [chochain/nanoFORTH#3]
Many links in the docs end up in Error 404, e.g.
https://github.com/chochain/nanoFORTH/blob/main/docs/page1.html

**Comment by chochain** [comment]
* The ~/blob/main/docs/* links following ~/docs/n4_*.md are used to generate Github pages (via doxygen). 
* They do cause confusion for users if clicked. 

I should keep them in gh-pages branch only instead. In my work queue, now!

**Comment by chochain** [comment]
docs/*.md kept in gh-pages branch now. Close this ticket.
