### ISSUE TITLE
Why is the result of binary comparsions not `0xffff` like in other Forths?

### ISSUE THREAD

**Issue by hyphenrf** [chochain/nanoFORTH#4]
This would allow boolean negation to be done with `NOT`, currently it's done with `0 =`.
The patch for this should be fairly simple I imagine:
https://github.com/chochain/nanoFORTH/blob/daf598fd7be8db9a647887addd741a5c9fbce302/src/n4_vm.cpp#L187-L190
the rhs expressions in the lines above would be surrounded with `-(...)`

**Comment by hyphenrf** [comment]
BTW if you believe this is an OK change but have a big backlog, just let me know and I'll send you a ready-made PR

**Comment by chochain** [comment]
Thank you. 
I didn't know most Forths use -1 as TRUE when I started nanoForth. It's an easy fix. Should show up in next release.

**Comment by hyphenrf** [comment]
with 603b4f5, this and #5 should now be resolved. big thanks ^^
it looks like instruction codes were switched around, so I'll redefine my words and report back (edit: all good).
although I'm sure it all works fine, and very likely that will be the case. marking both issues as resolved.
