### ISSUE TITLE
Is there a reason for preferring signed right-shifts over unsigned?

### ISSUE THREAD

**Issue by hyphenrf** [chochain/nanoFORTH#5]
Currently, right-shifting is defined like so:
https://github.com/chochain/nanoFORTH/blob/daf598fd7be8db9a647887addd741a5c9fbce302/src/n4_vm.cpp#L186
https://github.com/chochain/nanoFORTH/blob/daf598fd7be8db9a647887addd741a5c9fbce302/src/n4_vm.cpp#L28
https://github.com/chochain/nanoFORTH/blob/daf598fd7be8db9a647887addd741a5c9fbce302/src/n4_core.h#L40
In effect, this makes the emitted right-shift arithmetic.

I believe the logical shift is the one we're more likely to need, and the one that's defined by the standard. If arithmetic shift is needed for whatever reason, it isn't difficult to define in terms of a logical one.

The change to allow for this would be minimal:
```c++
_X(17,
    S16 a = POP();
    TOS = static_cast<U16>(TOS) >> a; 
);
```

An alternative would be to define both `RSH` and `ASR`

**Comment by chochain** [comment]
Thank you for the review and I do agree that RSH should be unsigned. Fix should show up in next release.
